apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: preprod-fusion-ms-hpa
  namespace: dev
  labels:
    env: preprod
    app: fusion-ms-ms
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: preprod-fusion-ms-deployment
  targetCPUUtilizationPercentage: 80